### ISSUE TITLE
cms question

### ISSUE THREAD

**Issue by panakour** [pointyfar/hubrix#1]
Is this to be let a client to manage content of it's hugo cms? Also is there any estimate time to be ready for production use?

**Comment by pointyfar** [comment]
Hi there,

I haven't looked at this project in the last few weeks, so I didn't see your message here. It's not really meant as a CMS for Hugo. It's more of a tool for configuring Hugo and building the templates.

It's a side-project for me for now, so I don't have a timeline just yet.
